### ISSUE TITLE
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

### ISSUE THREAD

**Issue by LGang** [kaivean/system_proxy#3]
![image](https://user-images.githubusercontent.com/11881950/122858948-c66e6c00-d34d-11eb-839c-fbb12aab7a0d.png)

**Comment by anisimowsjava** [comment]
@kaivean  Please accept this pull request

**Comment by rollin-s** [comment]
@kaivean Can you please accept this pull request ? :)

**Comment by rollin-s** [comment]
@kaivean Looks good on my side ! Thank you ! :) 
👍

**Comment by vanlooverenkoen** [comment]
this can be closed
